export const keys = [
  {
    name: "C major",
    notes: [
      { number: "I", note: "C Major" },
      { number: "II", note: "D Minor" },
      { number: "III", note: "E Minor" },
      { number: "IV", note: "F Major" },
      { number: "V", note: "G Major" },
      { number: "VI", note: "A Minor" },
      { number: "VII", note: "B Dim" },
    ],
  },
  {
    name: "D major",
    notes: [
      { number: "I", note: "D Major" },
      { number: "II", note: "E Minor" },
      { number: "III", note: "F# Minor" },
      { number: "IV", note: "G Major" },
      { number: "V", note: "A Major" },
      { number: "VI", note: "B Minor" },
      { number: "VII", note: "C# Dim" },
    ],
  },
  {
    name: "E major",
    notes: [
      { number: "I", note: "E Major" },
      { number: "II", note: "F# Minor" },
      { number: "III", note: "G# Minor" },
      { number: "IV", note: "A Major" },
      { number: "V", note: "B Major" },
      { number: "VI", note: "C# Minor" },
      { number: "VII", note: "D# Dim" },
    ],
  },
  {
    name: "F major",
    notes: [
      { number: "I", note: "F Major" },
      { number: "II", note: "G Minor" },
      { number: "III", note: "A Minor" },
      { number: "IV", note: "Bb Major" },
      { number: "V", note: "C Major" },
      { number: "VI", note: "D Minor" },
      { number: "VII", note: "E Dim" },
    ],
  },
  {
    name: "G major",
    notes: [
      { number: "I", note: "G Major" },
      { number: "II", note: "A Minor" },
      { number: "III", note: "B Minor" },
      { number: "IV", note: "C Major" },
      { number: "V", note: "D Major" },
      { number: "VI", note: "E Minor" },
      { number: "VII", note: "F# Dim" },
    ],
  },
  {
    name: "A major",
    notes: [
      { number: "I", note: "A Major" },
      { number: "II", note: "B Minor" },
      { number: "III", note: "C# Minor" },
      { number: "IV", note: "D Major" },
      { number: "V", note: "E Major" },
      { number: "VI", note: "F# Minor" },
      { number: "VII", note: "G# Dim" },
    ],
  },
  {
    name: "B major",
    notes: [
      { number: "I", note: "B Major" },
      { number: "II", note: "C# Minor" },
      { number: "III", note: "D# Minor" },
      { number: "IV", note: "E Major" },
      { number: "V", note: "F# Major" },
      { number: "VI", note: "G Minor" },
      { number: "VII", note: "A# Dim" },
    ],
  },
  {
    name: "C minor",
    notes: [
      { number: "I", note: "C Minor" },
      { number: "II", note: "D Dim" },
      { number: "III", note: "Eb Major" },
      { number: "IV", note: "F Minor" },
      { number: "V", note: "G Minor" },
      { number: "VI", note: "Ab Major" },
      { number: "VII", note: "Bb Major" },
    ],
  },
  {
    name: "D minor",
    notes: [
      { number: "I", note: "D Minor" },
      { number: "II", note: "E Dim" },
      { number: "III", note: "F Major" },
      { number: "IV", note: "G Minor" },
      { number: "V", note: "A Minor" },
      { number: "VI", note: "Bb Major" },
      { number: "VII", note: "C Major" },
    ],
  },
  {
    name: "E minor",
    notes: [
      { number: "I", note: "E Minor" },
      { number: "II", note: "F# Dim" },
      { number: "III", note: "G Major" },
      { number: "IV", note: "A Minor" },
      { number: "V", note: "B Minor" },
      { number: "VI", note: "C Major" },
      { number: "VII", note: "D Major" },
    ],
  },
  {
    name: "F minor",
    notes: [
      { number: "I", note: "F Minor" },
      { number: "II", note: "G Dim" },
      { number: "III", note: "Ab Major" },
      { number: "IV", note: "Bb Minor" },
      { number: "V", note: "C Minor" },
      { number: "VI", note: "Db Major" },
      { number: "VII", note: "Eb Major" },
    ],
  },
  {
    name: "G minor",
    notes: [
      { number: "I", note: "G Minor" },
      { number: "II", note: "A Dim" },
      { number: "III", note: "Bb Major" },
      { number: "IV", note: "C Minor" },
      { number: "V", note: "D Minor" },
      { number: "VI", note: "Eb Major" },
      { number: "VII", note: "F Major" },
    ],
  },
  {
    name: "A minor",
    notes: [
      { number: "I", note: "A Minor" },
      { number: "II", note: "B Dim" },
      { number: "III", note: "C Major" },
      { number: "IV", note: "D Minor" },
      { number: "V", note: "E Minor" },
      { number: "VI", note: "F Major" },
      { number: "VII", note: "G Major" },
    ],
  },
  {
    name: "B minor",
    notes: [
      { number: "I", note: "B Minor" },
      { number: "II", note: "C# Dim" },
      { number: "III", note: "D Major" },
      { number: "IV", note: "E Minor" },
      { number: "V", note: "F# Minor" },
      { number: "VI", note: "Gb Major" },
      { number: "VII", note: "Ab Major" },
    ],
  },
];
